# Generated by Django 5.1.7 on 2025-03-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp_ecommerce", "0002_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
